/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Estuardo Salay
 */
public class FrmVistaAdmin extends javax.swing.JFrame {

    /**
     * Creates new form vistaAdmin
     */
    public FrmVistaAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVistaAdminIngresarU = new javax.swing.JButton();
        btnVistaAdminIngresarM = new javax.swing.JButton();
        btnVistaAdminVerMesas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnVistaAdminHistorial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CRUD ADMIN");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVistaAdminIngresarU.setText("Ingresar Usuarios");
        btnVistaAdminIngresarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVistaAdminIngresarUActionPerformed(evt);
            }
        });
        getContentPane().add(btnVistaAdminIngresarU, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 30, -1, -1));

        btnVistaAdminIngresarM.setText("Ingresar Menu");
        getContentPane().add(btnVistaAdminIngresarM, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 64, 120, -1));

        btnVistaAdminVerMesas.setText("Ver Mesas");
        getContentPane().add(btnVistaAdminVerMesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 104, 120, -1));

        jLabel1.setText("Historial");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 144, -1, -1));

        btnVistaAdminHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Historial1.png"))); // NOI18N
        getContentPane().add(btnVistaAdminHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 166, 44, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVistaAdminIngresarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVistaAdminIngresarUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVistaAdminIngresarUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVistaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnVistaAdminHistorial;
    public javax.swing.JButton btnVistaAdminIngresarM;
    public javax.swing.JButton btnVistaAdminIngresarU;
    public javax.swing.JButton btnVistaAdminVerMesas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
